#!/bin/bash

set -e

FILE='checksums-test.tmp'
trap "rm -f $FILE" EXIT
echo 'checksums' >$FILE
FILE_SHA1='eeaeb6659e4e5389f4f61dce515f8da2407e3a1d'
FILE_MD5='62b75f24753634ab68aa2e12a2de4aee'

# cleaning the attributes
getfattr $FILE | while read attr; do
    case $attr in
        user.md5|user.sha1)
            setfattr -x $attr $FILE 
            ;;
    esac
done

# calculating checksums
./checksums $FILE

# checking the results
getfattr --dump --encoding=hex $FILE | while read attr; do
    case $attr in
        user.md5=*)
            test $attr = "user.md5=0x$FILE_MD5"
            ;;
        user.sha1=*)
            test $attr = "user.sha1=0x$FILE_SHA1"
            ;;
    esac
done

